// Icelandic postcode data (number, place name in nominative + dative, region,
// description, kind).
//
// This data is ported from Sveinbjörn Þórðarson's `iceaddr` project
// (https://github.com/sveinbjornt/iceaddr), src/iceaddr/postcodes.py, which is
// licensed BSD-3-Clause:
//
//   Copyright (c) 2018-2025 Sveinbjorn Thordarson.
//
// The original postcode list is provided by Postur.is; the nominative place
// names were declined from the dative by iceaddr using Miðeind's GreynirPackage.
// See NOTICE.md for the full BSD-3-Clause text. This is the only bundled data in
// the package — address records themselves are fetched live from HMS, never
// redistributed here.

export interface Postcode {
  /** Three-digit Icelandic postcode, e.g. "101". */
  code: string;
  /** Place name, nominative case (e.g. "Reykjavík"). */
  nominative: string;
  /** Place name, dative case (e.g. "Reykjavík"). */
  dative: string;
  /** Region, nominative (e.g. "Höfuðborgarsvæðið"). */
  region: string;
  /** Region, dative (e.g. "Höfuðborgarsvæðinu"). */
  regionDative: string;
  /** Free-text description of the area (e.g. "Miðborg"). */
  description: string;
  /** Postcode kind as classified upstream (e.g. "Stærra dreifbýli"). */
  kind: string;
}

type PostcodeData = Omit<Postcode, "code">;

const DATA: Record<string, PostcodeData> = {
  "101": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Miðborg",
    kind: "Stærra dreifbýli",
  },
  "102": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Vatnsmýri og Skerjafjörður",
    kind: "Stærra dreifbýli",
  },
  "103": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Háaleitis- og Bústaðahverfi",
    kind: "Stærra dreifbýli",
  },
  "104": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Laugardalur",
    kind: "Stærra dreifbýli",
  },
  "105": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Hlíðar",
    kind: "Stærra dreifbýli",
  },
  "107": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Vesturbær",
    kind: "Stærra dreifbýli",
  },
  "108": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Háaleitis- og Bústaðahverfi",
    kind: "Stærra dreifbýli",
  },
  "109": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Breiðholt",
    kind: "Stærra dreifbýli",
  },
  "110": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Árbær",
    kind: "Stærra dreifbýli",
  },
  "111": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Breiðholt",
    kind: "Stærra dreifbýli",
  },
  "112": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Grafarvogur",
    kind: "Stærra dreifbýli",
  },
  "113": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Grafarholt og Úlfarsárdalur",
    kind: "Stærra dreifbýli",
  },
  "116": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Kjalarnes",
    kind: "Stærra dreifbýli",
  },
  "121": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "123": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "124": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "125": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "127": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "128": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "129": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "130": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "132": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "150": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Dreifbýli",
  },
  "155": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Dreifbýli",
  },
  "161": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Dreifbýli",
  },
  "162": {
    nominative: "Reykjavík",
    dative: "Reykjavík",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Dreifbýli",
  },
  "170": {
    nominative: "Seltjarnarnes",
    dative: "Seltjarnarnesi",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "172": {
    nominative: "Seltjarnarnes",
    dative: "Seltjarnarnesi",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "190": {
    nominative: "Vogar",
    dative: "Vogum",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "191": {
    nominative: "Vogar",
    dative: "Vogum",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "200": {
    nominative: "Kópavogur",
    dative: "Kópavogi",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "201": {
    nominative: "Kópavogur",
    dative: "Kópavogi",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "202": {
    nominative: "Kópavogur",
    dative: "Kópavogi",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "203": {
    nominative: "Kópavogur",
    dative: "Kópavogi",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "206": {
    nominative: "Kópavogur",
    dative: "Kópavogi",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Dreifbýli",
  },
  "210": {
    nominative: "Garðabær",
    dative: "Garðabæ",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "212": {
    nominative: "Garðabær",
    dative: "Garðabæ",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "220": {
    nominative: "Hafnarfjörður",
    dative: "Hafnarfirði",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "221": {
    nominative: "Hafnarfjörður",
    dative: "Hafnarfirði",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "222": {
    nominative: "Hafnarfjörður",
    dative: "Hafnarfirði",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Pósthólf",
  },
  "225": {
    nominative: "Garðabær",
    dative: "Garðabæ",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "230": {
    nominative: "Reykjanesbær",
    dative: "Reykjanesbæ",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "232": {
    nominative: "Reykjanesbær",
    dative: "Reykjanesbæ",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Pósthólf",
  },
  "233": {
    nominative: "Reykjanesbær",
    dative: "Reykjanesbæ",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "235": {
    nominative: "Keflavíkurflugvöllur",
    dative: "Keflavíkurflugvelli",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "Keflavíkurflugvöllur",
    kind: "Stærra dreifbýli",
  },
  "240": {
    nominative: "Grindavík",
    dative: "Grindavík",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "241": {
    nominative: "Grindavík",
    dative: "Grindavík",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "245": {
    nominative: "Sandgerði",
    dative: "Sandgerði",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "246": {
    nominative: "Sandgerði",
    dative: "Sandgerði",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "250": {
    nominative: "Garður",
    dative: "Garði",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "251": {
    nominative: "Garður",
    dative: "Garði",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "260": {
    nominative: "Reykjanesbær",
    dative: "Reykjanesbæ",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "262": {
    nominative: "Reykjanesbær",
    dative: "Reykjanesbæ",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "Ásbrú",
    kind: "Stærra dreifbýli",
  },
  "270": {
    nominative: "Mosfellsbær",
    dative: "Mosfellsbæ",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "271": {
    nominative: "Mosfellsbær",
    dative: "Mosfellsbæ",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "276": {
    nominative: "Kjós",
    dative: "Kjós",
    region: "Höfuðborgarsvæðið",
    regionDative: "Höfuðborgarsvæðinu",
    description: "Kjós",
    kind: "Stærra dreifbýli",
  },
  "300": {
    nominative: "Akranes",
    dative: "Akranesi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "301": {
    nominative: "Akranes",
    dative: "Akranesi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "302": {
    nominative: "Akranes",
    dative: "Akranesi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Pósthólf",
  },
  "310": {
    nominative: "Borgarnes",
    dative: "Borgarnesi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "311": {
    nominative: "Borgarnes",
    dative: "Borgarnesi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "320": {
    nominative: "Reykholt",
    dative: "Reykholti",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "340": {
    nominative: "Stykkishólmur",
    dative: "Stykkishólmi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "341": {
    nominative: "Stykkishólmur",
    dative: "Stykkishólmi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "342": {
    nominative: "Stykkishólmur",
    dative: "Stykkishólmi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "345": {
    nominative: "Flatey",
    dative: "Flatey",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "350": {
    nominative: "Grundarfjörður",
    dative: "Grundarfirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "351": {
    nominative: "Grundarfjörður",
    dative: "Grundarfirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "355": {
    nominative: "Ólafsvík",
    dative: "Ólafsvík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "356": {
    nominative: "Snæfellsbær",
    dative: "Snæfellsbæ",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "360": {
    nominative: "Hellissandur",
    dative: "Hellissandi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "370": {
    nominative: "Búðardalur",
    dative: "Búðardal",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "371": {
    nominative: "Búðardalur",
    dative: "Búðardal",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "380": {
    nominative: "Reykhólahreppur",
    dative: "Reykhólahreppi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "381": {
    nominative: "Reykhólahreppur",
    dative: "Reykhólahreppi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "400": {
    nominative: "Ísafjörður",
    dative: "Ísafirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "401": {
    nominative: "Ísafjörður",
    dative: "Ísafirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "410": {
    nominative: "Hnífsdalur",
    dative: "Hnífsdal",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "415": {
    nominative: "Bolungarvík",
    dative: "Bolungarvík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "416": {
    nominative: "Bolungarvík",
    dative: "Bolungarvík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "420": {
    nominative: "Súðavík",
    dative: "Súðavík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "421": {
    nominative: "Súðavík",
    dative: "Súðavík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "425": {
    nominative: "Flateyri",
    dative: "Flateyri",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "426": {
    nominative: "Flateyri",
    dative: "Flateyri",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "430": {
    nominative: "Suðureyri",
    dative: "Suðureyri",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "431": {
    nominative: "Suðureyri",
    dative: "Suðureyri",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "450": {
    nominative: "Patreksfjörður",
    dative: "Patreksfirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "451": {
    nominative: "Patreksfjörður",
    dative: "Patreksfirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "460": {
    nominative: "Tálknafjörður",
    dative: "Tálknafirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "461": {
    nominative: "Tálknafjörður",
    dative: "Tálknafirði",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "465": {
    nominative: "Bíldudalur",
    dative: "Bíldudal",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "466": {
    nominative: "Bíldudalur",
    dative: "Bíldudal",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "470": {
    nominative: "Þingeyri",
    dative: "Þingeyri",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "471": {
    nominative: "Þingeyri",
    dative: "Þingeyri",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "500": {
    nominative: "Staður",
    dative: "Stað",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "510": {
    nominative: "Hólmavík",
    dative: "Hólmavík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "511": {
    nominative: "Hólmavík",
    dative: "Hólmavík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "512": {
    nominative: "Hólmavík",
    dative: "Hólmavík",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "520": {
    nominative: "Drangsnes",
    dative: "Drangsnesi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "524": {
    nominative: "Árneshreppur",
    dative: "Árneshreppi",
    region: "Vesturland og Vestfirðir",
    regionDative: "Vesturlandi og Vestfjörðum",
    description: "",
    kind: "Dreifbýli",
  },
  "530": {
    nominative: "Hvammstangi",
    dative: "Hvammstanga",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "531": {
    nominative: "Hvammstangi",
    dative: "Hvammstanga",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "540": {
    nominative: "Blönduós",
    dative: "Blönduósi",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "541": {
    nominative: "Blönduós",
    dative: "Blönduósi",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "545": {
    nominative: "Skagaströnd",
    dative: "Skagaströnd",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "546": {
    nominative: "Skagaströnd",
    dative: "Skagaströnd",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "550": {
    nominative: "Sauðárkrókur",
    dative: "Sauðárkróki",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "551": {
    nominative: "Sauðárkrókur",
    dative: "Sauðárkróki",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "560": {
    nominative: "Varmahlíð",
    dative: "Varmahlíð",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "561": {
    nominative: "Varmahlíð",
    dative: "Varmahlíð",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "565": {
    nominative: "Hofsós",
    dative: "Hofsósi",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "566": {
    nominative: "Hofsós",
    dative: "Hofsósi",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "570": {
    nominative: "Fljót",
    dative: "Fljótum",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "580": {
    nominative: "Siglufjörður",
    dative: "Siglufirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "581": {
    nominative: "Siglufjörður",
    dative: "Siglufirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "600": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "601": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "602": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Pósthólf",
  },
  "603": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "604": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "605": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "606": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "607": {
    nominative: "Akureyri",
    dative: "Akureyri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "610": {
    nominative: "Grenivík",
    dative: "Grenivík",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "611": {
    nominative: "Grímsey",
    dative: "Grímsey",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "616": {
    nominative: "Grenivík",
    dative: "Grenivík",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "620": {
    nominative: "Dalvík",
    dative: "Dalvík",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "621": {
    nominative: "Dalvík",
    dative: "Dalvík",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "625": {
    nominative: "Ólafsfjörður",
    dative: "Ólafsfirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "626": {
    nominative: "Ólafsfjörður",
    dative: "Ólafsfirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "630": {
    nominative: "Hrísey",
    dative: "Hrísey",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "640": {
    nominative: "Húsavík",
    dative: "Húsavík",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "641": {
    nominative: "Húsavík",
    dative: "Húsavík",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "645": {
    nominative: "Fosshóll",
    dative: "Fosshóli",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "650": {
    nominative: "Laugar",
    dative: "Laugum",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "660": {
    nominative: "Mývatn",
    dative: "Mývatni",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "670": {
    nominative: "Kópasker",
    dative: "Kópaskeri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "671": {
    nominative: "Kópasker",
    dative: "Kópaskeri",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "675": {
    nominative: "Raufarhöfn",
    dative: "Raufarhöfn",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "676": {
    nominative: "Raufarhöfn",
    dative: "Raufarhöfn",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "680": {
    nominative: "Þórshöfn",
    dative: "Þórshöfn",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "681": {
    nominative: "Þórshöfn",
    dative: "Þórshöfn",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "685": {
    nominative: "Bakkafjörður",
    dative: "Bakkafirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "686": {
    nominative: "Bakkafjörður",
    dative: "Bakkafirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "690": {
    nominative: "Vopnafjörður",
    dative: "Vopnafirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "691": {
    nominative: "Vopnafjörður",
    dative: "Vopnafirði",
    region: "Norðurland",
    regionDative: "Norðurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "700": {
    nominative: "Egilsstaðir",
    dative: "Egilsstöðum",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "701": {
    nominative: "Egilsstaðir",
    dative: "Egilsstöðum",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "710": {
    nominative: "Seyðisfjörður",
    dative: "Seyðisfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "711": {
    nominative: "Seyðisfjörður",
    dative: "Seyðisfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "715": {
    nominative: "Mjóifjörður",
    dative: "Mjóafirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "720": {
    nominative: "Borgarfjörður eystra",
    dative: "Borgarfirði eystra",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "721": {
    nominative: "Borgarfjörður eystra",
    dative: "Borgarfirði eystra",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "730": {
    nominative: "Reyðarfjörður",
    dative: "Reyðarfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "731": {
    nominative: "Reyðarfjörður",
    dative: "Reyðarfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "735": {
    nominative: "Eskifjörður",
    dative: "Eskifirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "736": {
    nominative: "Eskifjörður",
    dative: "Eskifirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "740": {
    nominative: "Neskaupstaður",
    dative: "Neskaupstað",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "741": {
    nominative: "Neskaupstaður",
    dative: "Neskaupstað",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "750": {
    nominative: "Fáskrúðsfjörður",
    dative: "Fáskrúðsfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "751": {
    nominative: "Fáskrúðsfjörður",
    dative: "Fáskrúðsfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "755": {
    nominative: "Stöðvarfjörður",
    dative: "Stöðvarfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "756": {
    nominative: "Stöðvarfjörður",
    dative: "Stöðvarfirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "760": {
    nominative: "Breiðdalsvík",
    dative: "Breiðdalsvík",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "761": {
    nominative: "Breiðdalsvík",
    dative: "Breiðdalsvík",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "765": {
    nominative: "Djúpivogur",
    dative: "Djúpavogi",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "766": {
    nominative: "Djúpivogur",
    dative: "Djúpavogi",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "780": {
    nominative: "Höfn í Hornafirði",
    dative: "Höfn í Hornafirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "781": {
    nominative: "Höfn í Hornafirði",
    dative: "Höfn í Hornafirði",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Dreifbýli",
  },
  "785": {
    nominative: "Öræfi",
    dative: "Öræfum",
    region: "Austurland",
    regionDative: "Austurlandi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "800": {
    nominative: "Selfoss",
    dative: "Selfossi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "801": {
    nominative: "Selfoss",
    dative: "Selfossi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "802": {
    nominative: "Selfoss",
    dative: "Selfossi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Pósthólf",
  },
  "803": {
    nominative: "Selfoss",
    dative: "Selfossi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "804": {
    nominative: "Selfoss",
    dative: "Selfossi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "805": {
    nominative: "Selfoss",
    dative: "Selfossi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "806": {
    nominative: "Selfoss",
    dative: "Selfossi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "810": {
    nominative: "Hveragerði",
    dative: "Hveragerði",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "815": {
    nominative: "Þorlákshöfn",
    dative: "Þorlákshöfn",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "816": {
    nominative: "Ölfus",
    dative: "Ölfusi",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "820": {
    nominative: "Eyrarbakki",
    dative: "Eyrarbakka",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "825": {
    nominative: "Stokkseyri",
    dative: "Stokkseyri",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "840": {
    nominative: "Laugarvatn",
    dative: "Laugarvatni",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "845": {
    nominative: "Flúðir",
    dative: "Flúðum",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "846": {
    nominative: "Flúðir",
    dative: "Flúðum",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "850": {
    nominative: "Hella",
    dative: "Hellu",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "851": {
    nominative: "Hella",
    dative: "Hellu",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "860": {
    nominative: "Hvolsvöllur",
    dative: "Hvolsvelli",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "861": {
    nominative: "Hvolsvöllur",
    dative: "Hvolsvelli",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "870": {
    nominative: "Vík",
    dative: "Vík",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "871": {
    nominative: "Vík",
    dative: "Vík",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "880": {
    nominative: "Kirkjubæjarklaustur",
    dative: "Kirkjubæjarklaustri",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "881": {
    nominative: "Kirkjubæjarklaustur",
    dative: "Kirkjubæjarklaustri",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Dreifbýli",
  },
  "900": {
    nominative: "Vestmannaeyjar",
    dative: "Vestmannaeyjum",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Stærra dreifbýli",
  },
  "902": {
    nominative: "Vestmannaeyjar",
    dative: "Vestmannaeyjum",
    region: "Suðurland og Reykjanes",
    regionDative: "Suðurlandi og Reykjanesi",
    description: "",
    kind: "Pósthólf",
  },
};

/** All bundled postcodes, keyed by their three-digit code. */
export const POSTCODES: Record<string, Postcode> = Object.fromEntries(
  Object.entries(DATA).map(([code, v]) => [code, { code, ...v }]),
);

/** Look up a single postcode's place + region info, or `undefined`. */
export function postcodeLookup(code: string | number): Postcode | undefined {
  return POSTCODES[String(code)];
}

/**
 * The set of known postcodes — pass this to `cleanAddressRow` /
 * `streamStadfangaskra` to filter address rows to real postcodes.
 */
export function knownPostcodes(): Set<string> {
  return new Set(Object.keys(POSTCODES));
}
